### ISSUE TITLE
Exception if certificates with shared CN field are used

### ISSUE THREAD

**Issue by hdznrrd** [oliverhaagh/MCP-Root#1]
# Error
```
2021-01-21 13:50:21.410 ERROR 1 --- [nio-8080-exec-3] o.h.engine.jdbc.spi.SqlExceptionHelper   : Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_7 ON PUBLIC.ROOT_CA(NAME) VALUES 1"; SQL statement: insert into root_ca (id, created_at, certificate, name) values (null, ?, ?, ?) [23505-200]
2021-01-21 13:50:21.437 ERROR 1 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint ["PUBLIC.CONSTRAINT_INDEX_7 ON PUBLIC.ROOT_CA(NAME) VALUES 1"; SQL statement: insert into root_ca (id, created_at, certificate, name) values (null, ?, ?, ?) [23505-200]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement] with root cause
```

# Reproducability
Can be triggered using https://github.com/hdznrrd/mcp-root-test/blob/main/cert_name_collision.sh

# Discussion
If you actually need a key to reference certificates with, pick something yourself and not rely on data the user provides _and_ controls.

Could be an auto-increment index of your database or the hash of the certificate itself.
The latter might have some benefits down the line if you need to find the entry for a specific certificate without enumerating all of them. However, this again enters whitespace handling territory and needs extra thought.

**Comment by oliverhaagh** [comment]
All tables already have an auto-increment index as the primary key, but the Attestor and RootCA tables also have a unique constraint on the 'name' column, which is of course not really thought through. A unique constraint on the hash of the certificate will definitely be better, but, as you also note, will also need to be thought through to tackle white space related issues.

**Comment by oliverhaagh** [comment]
https://github.com/oliverhaagh/MCP-Root/commit/c91adde6cb23265cf0a14531e4da7076a5c6e385

**Comment by hdznrrd** [comment]
I think there's a regression bug now.
I can no longer get the new version to run on my end.

```
2021-01-26 15:17:36.362  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: 
Migration V1__init.sql failed
-----------------------------
SQL State  : HYC00
Error Code : 50100
Message    : Feature not supported: "Index on BLOB or CLOB column: ""CERTIFICATE"" MEDIUMTEXT NOT NULL"; SQL statement:
CREATE TABLE `root_ca` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `created_at` DATETIME NOT NULL,
    `certificate` MEDIUMTEXT NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE (`certificate`)
) [50100-200]
Location   : db/migration/V1__init.sql (/file:/root-ca-list-0.0.1-SNAPSHOT.war!/WEB-INF/classes!/db/migration/V1__init.sql)
Line       : 17
Statement  : CREATE TABLE `root_ca` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `created_at` DATETIME NOT NULL,
    `certificate` MEDIUMTEXT NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE (`certificate`)
)
```

And a whole bunch of exceptions that look similar/related.

**Comment by oliverhaagh** [comment]
Sorry that might be my bad - apart from the changed indexes I also renamed the original db init file from V20200904135622__init.sql to V1__init.sql and this makes flywaydb complain. The fastest fix is to drop your current tables and then run again. Else I can also revert to the old init file and then make a new db migration point with the new changes. Which one would you prefer?

**Comment by hdznrrd** [comment]
How odd, I would have expected there not being any carry-over when using the Docker-based setup (which I do).
Is that not building entirely from scratch?

**Comment by oliverhaagh** [comment]
The Docker-based setup should be building entirely from scratch, but if you are using an actual mysql/mariadb instance for persistence flywaydb will store the migration history in a table called 'flyway_schema_history', and because I overwrote the initial state of the database instead of making a new migration point flywaydb will complain about it because the new version is different from the one it knew.

**Comment by hdznrrd** [comment]
Hmm, nope, not here. Unless there is something happening under the hood that I'm entirely overlooking right now.
Here's what I did:

- pulled the latest MCP-Root
- deleted any stray containers
- deleted the the mcp image created based on the Dockerfile
- run my `./rebuild_and_launch_root.sh` script

Omitting the first ./mvnw run to build the .war (successful) and concentrating only on the output of docker building as well as running the resulting container I get the following:

```Sending build context to Docker daemon  54.84MB
Step 1/4 : FROM openjdk:8-jre
 ---> 608a4320629a
Step 2/4 : RUN mkdir -p /conf
 ---> Using cache
 ---> a72fd5a5d1af
Step 3/4 : ADD root-ca-list-0.0.1-SNAPSHOT.war .
 ---> 84d529e51435
Step 4/4 : CMD ["java", "-Dspring.profiles.active=prod", "-jar", "root-ca-list-0.0.1-SNAPSHOT.war", "--spring.config.location=/conf/application.yaml"]
 ---> Running in 6f63dfeb3ec9
Removing intermediate container 6f63dfeb3ec9
 ---> d0080c2e719b
Successfully built d0080c2e719b
Successfully tagged mcp:latest

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.3.4.RELEASE)

2021-01-26 15:59:31.818  INFO 1 --- [           main] n.m.rootcalist.RootCaListApplication     : Starting RootCaListApplication v0.0.1-SNAPSHOT on 4beee4a88313 with PID 1 (/root-ca-list-0.0.1-SNAPSHOT.war started by root in /)
2021-01-26 15:59:31.823  INFO 1 --- [           main] n.m.rootcalist.RootCaListApplication     : The following profiles are active: prod
2021-01-26 15:59:33.805  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFERRED mode.
2021-01-26 15:59:34.053  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 233ms. Found 4 JPA repository interfaces.
2021-01-26 15:59:35.474  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2021-01-26 15:59:35.495  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-01-26 15:59:35.497  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.38]
2021-01-26 15:59:37.736  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-01-26 15:59:37.736  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 5803 ms
2021-01-26 15:59:38.006  INFO 1 --- [           main] o.f.c.internal.license.VersionPrinter    : Flyway Community Edition 6.4.4 by Redgate
2021-01-26 15:59:38.022  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2021-01-26 15:59:38.597  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2021-01-26 15:59:38.638  INFO 1 --- [           main] o.f.c.internal.database.DatabaseFactory  : Database: jdbc:h2:mem:9f4ae052-0cdc-44d4-8b75-6d009a0b974c (H2 1.4)
2021-01-26 15:59:38.775  INFO 1 --- [           main] o.f.core.internal.command.DbValidate     : Successfully validated 1 migration (execution time 00:00.044s)
2021-01-26 15:59:38.804  INFO 1 --- [           main] o.f.c.i.s.JdbcTableSchemaHistory         : Creating Schema History table "PUBLIC"."flyway_schema_history" ...
2021-01-26 15:59:38.897  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Current version of schema "PUBLIC": << Empty Schema >>
2021-01-26 15:59:38.911  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "PUBLIC" to version 1 - init
2021-01-26 15:59:38.936 ERROR 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migration of schema "PUBLIC" to version 1 - init failed! Please restore backups and roll back database and code!
2021-01-26 15:59:38.967  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: 
Migration V1__init.sql failed
-----------------------------
SQL State  : HYC00
Error Code : 50100
Message    : Feature not supported: "Index on BLOB or CLOB column: ""CERTIFICATE"" MEDIUMTEXT NOT NULL"; SQL statement:
CREATE TABLE `root_ca` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `created_at` DATETIME NOT NULL,
    `certificate` MEDIUMTEXT NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE (`certificate`)
) [50100-200]
Location   : db/migration/V1__init.sql (/file:/root-ca-list-0.0.1-SNAPSHOT.war!/WEB-INF/classes!/db/migration/V1__init.sql)
Line       : 17
Statement  : CREATE TABLE `root_ca` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `created_at` DATETIME NOT NULL,
    `certificate` MEDIUMTEXT NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE (`certificate`)
)

2021-01-26 15:59:38.968  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2021-01-26 15:59:38.981  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2021-01-26 15:59:38.990  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2021-01-26 15:59:39.020  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-01-26 15:59:39.038 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: 
Migration V1__init.sql failed
-----------------------------
SQL State  : HYC00
Error Code : 50100
Message    : Feature not supported: "Index on BLOB or CLOB column: ""CERTIFICATE"" MEDIUMTEXT NOT NULL"; SQL statement:
CREATE TABLE `root_ca` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `created_at` DATETIME NOT NULL,
    `certificate` MEDIUMTEXT NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE (`certificate`)
) [50100-200]
Location   : db/migration/V1__init.sql (/file:/root-ca-list-0.0.1-SNAPSHOT.war!/WEB-INF/classes!/db/migration/V1__init.sql)
Line       : 17
Statement  : CREATE TABLE `root_ca` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `created_at` DATETIME NOT NULL,
    `certificate` MEDIUMTEXT NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE (`certificate`)
)

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1794) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:311) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1109) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.4.RELEASE.jar!/:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) [spring-boot-2.3.4.RELEASE.jar!/:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.3.4.RELEASE.jar!/:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.3.4.RELEASE.jar!/:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.3.4.RELEASE.jar!/:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.4.RELEASE.jar!/:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.4.RELEASE.jar!/:2.3.4.RELEASE]
	at net.maritimeconnectivity.rootcalist.RootCaListApplication.main(RootCaListApplication.java:30) [classes!/:0.0.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_275]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_275]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_275]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [root-ca-list-0.0.1-SNAPSHOT.war:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) [root-ca-list-0.0.1-SNAPSHOT.war:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [root-ca-list-0.0.1-SNAPSHOT.war:0.0.1-SNAPSHOT]
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59) [root-ca-list-0.0.1-SNAPSHOT.war:0.0.1-SNAPSHOT]
Caused by: org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: 
Migration V1__init.sql failed
-----------------------------
SQL State  : HYC00
Error Code : 50100
Message    : Feature not supported: "Index on BLOB or CLOB column: ""CERTIFICATE"" MEDIUMTEXT NOT NULL"; SQL statement:
CREATE TABLE `root_ca` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `created_at` DATETIME NOT NULL,
    `certificate` MEDIUMTEXT NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE (`certificate`)
) [50100-200]
Location   : db/migration/V1__init.sql (/file:/root-ca-list-0.0.1-SNAPSHOT.war!/WEB-INF/classes!/db/migration/V1__init.sql)
Line       : 17
Statement  : CREATE TABLE `root_ca` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `created_at` DATETIME NOT NULL,
    `certificate` MEDIUMTEXT NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE (`certificate`)
)

	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:369) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.internal.command.DbMigrate.access$200(DbMigrate.java:54) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.internal.command.DbMigrate$3.call(DbMigrate.java:282) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:279) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:244) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:54) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:162) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:159) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate$1.call(TableLockingExecutionTemplate.java:38) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate.execute(TableLockingExecutionTemplate.java:33) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.internal.database.base.Connection.lock(Connection.java:129) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:140) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:159) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:137) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:199) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:159) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.Flyway.execute(Flyway.java:530) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.Flyway.migrate(Flyway.java:159) ~[flyway-core-6.4.4.jar!/:na]
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:65) ~[spring-boot-autoconfigure-2.3.4.RELEASE.jar!/:2.3.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
	... 27 common frames omitted
Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: 
Migration V1__init.sql failed
-----------------------------
SQL State  : HYC00
Error Code : 50100
Message    : Feature not supported: "Index on BLOB or CLOB column: ""CERTIFICATE"" MEDIUMTEXT NOT NULL"; SQL statement:
CREATE TABLE `root_ca` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `created_at` DATETIME NOT NULL,
    `certificate` MEDIUMTEXT NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE (`certificate`)
) [50100-200]
Location   : db/migration/V1__init.sql (/file:/root-ca-list-0.0.1-SNAPSHOT.war!/WEB-INF/classes!/db/migration/V1__init.sql)
Line       : 17
Statement  : CREATE TABLE `root_ca` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `created_at` DATETIME NOT NULL,
    `certificate` MEDIUMTEXT NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE (`certificate`)
)

	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:275) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:220) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:127) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:88) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.access$000(SqlMigrationExecutor.java:33) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor$1.call(SqlMigrationExecutor.java:77) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor$1.call(SqlMigrationExecutor.java:74) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:28) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:74) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:366) ~[flyway-core-6.4.4.jar!/:na]
	... 49 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLFeatureNotSupportedException: Feature not supported: "Index on BLOB or CLOB column: ""CERTIFICATE"" MEDIUMTEXT NOT NULL"; SQL statement:
CREATE TABLE `root_ca` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `created_at` DATETIME NOT NULL,
    `certificate` MEDIUMTEXT NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE (`certificate`)
) [50100-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:507) ~[h2-1.4.200.jar!/:na]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429) ~[h2-1.4.200.jar!/:na]
	at org.h2.message.DbException.get(DbException.java:205) ~[h2-1.4.200.jar!/:na]
	at org.h2.message.DbException.get(DbException.java:181) ~[h2-1.4.200.jar!/:na]
	at org.h2.message.DbException.getUnsupportedException(DbException.java:269) ~[h2-1.4.200.jar!/:na]
	at org.h2.index.BaseIndex.checkIndexColumnTypes(BaseIndex.java:76) ~[h2-1.4.200.jar!/:na]
	at org.h2.mvstore.db.MVSecondaryIndex.<init>(MVSecondaryIndex.java:56) ~[h2-1.4.200.jar!/:na]
	at org.h2.mvstore.db.MVTable.addIndex(MVTable.java:366) ~[h2-1.4.200.jar!/:na]
	at org.h2.command.ddl.AlterTableAddConstraint.createIndex(AlterTableAddConstraint.java:298) ~[h2-1.4.200.jar!/:na]
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:176) ~[h2-1.4.200.jar!/:na]
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:78) ~[h2-1.4.200.jar!/:na]
	at org.h2.command.ddl.CommandWithColumns.createConstraints(CommandWithColumns.java:83) ~[h2-1.4.200.jar!/:na]
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:133) ~[h2-1.4.200.jar!/:na]
	at org.h2.command.CommandContainer.update(CommandContainer.java:198) ~[h2-1.4.200.jar!/:na]
	at org.h2.command.Command.executeUpdate(Command.java:251) ~[h2-1.4.200.jar!/:na]
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:228) ~[h2-1.4.200.jar!/:na]
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:201) ~[h2-1.4.200.jar!/:na]
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95) ~[HikariCP-3.4.5.jar!/:na]
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-3.4.5.jar!/:na]
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:244) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:111) ~[flyway-core-6.4.4.jar!/:na]
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:208) ~[flyway-core-6.4.4.jar!/:na]
	... 57 common frames omitted
```

**Comment by oliverhaagh** [comment]
Hmm, I actually don't know how you got it working up until now then as running with the 'prod' profile actually requires a connection to an actual db instance... if there was some kind of magic going on under the hood I would definitely want to know what it was... ^^'

**Comment by hdznrrd** [comment]
Excellent, now we're two confused guys and none the wiser :D 
Now that I think about it that is odd indeed. Since it actually worked with the Dockerfile before and I know for a fact that the Dockerfile explicitly set the prod env.
For some reason it did work in the past though.

I've now set the env to test in the Dockerfile via the parameter passed in the CMD entry.
It comes up recognizing this: `n.m.rootcalist.RootCaListApplication     : The following profiles are active: testBut`
But it still fails with the migration of schema PUBLIC to version 1.

**Comment by oliverhaagh** [comment]
It seems like spring boot is falling back to an in-memory database when it can't get a connection to an actual database, and for some reason that in-memory doesn't support making a unique constraint on columns with the MEDIUMTEXT type... I will try to see if there is some kind of fix to get this working.

**Comment by hdznrrd** [comment]
Ah! That makes sense :)

**Comment by oliverhaagh** [comment]
I have not figured out how to change the behavior of the embedded db that spring boot falls back to. Instead I have made a docker-compose setup that also contains a mysql container in the docker folder which should hopefully make it as easy to test. 
Also I think I found a solution to the problem of ensuring uniqueness on certificates - basically I added an extra column in the tables for root CAs and attestors that contains a sha256 hash of the certificate with all whitespace and newline characters removed and made the unique constraint on that column.

**Comment by hdznrrd** [comment]
The change you applied worked for me (half) after some massaging (see PR #2).
I then ran into a regression (#3)
