### ISSUE TITLE
Value too long for column "certificate VARCHAR(255)"

### ISSUE THREAD

**Issue by hdznrrd** [oliverhaagh/MCP-Root#3]
- Upon trying to store a certificate to the database it fails with `value too long for column "certificate VARCHAR(255)"`
- The error is then reported falsely as `New root CA could not be persisted because it already exists`

## Reproducing it
- Use the current version off https://github.com/hdznrrd/mcp-root-test/blob/main/cert_name_collision.sh from the https://github.com/hdznrrd/mcp-root-test/ repo.
- The MCP-Root submodule should point to the version of MCP-Root based on PR #2
- When the first cert is submitted, it directly fails as follows:

```
ca-list_1  | 2021-01-29 12:53:38.698  INFO 1 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
ca-list_1  | 2021-01-29 12:53:38.711  INFO 1 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 13 ms
ca-list_1  | 2021-01-29 12:53:41.597  WARN 1 --- [nio-8080-exec-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 22001, SQLState: 22001
ca-list_1  | 2021-01-29 12:53:41.598 ERROR 1 --- [nio-8080-exec-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : Value too long for column "certificate VARCHAR(255)": "STRINGDECODE('-----BEGIN CERTIFICATE-----\nMIICVzCCAd6gAwIBAgIUSnkv6uVM1r+3fDwKpx13XcMOOn0wCgYIKoZIzj0EAwIw\nYzELMAkGA1UEBhMCREU... (871)"; SQL statement:
ca-list_1  | insert into root_ca (id, created_at, certificate, name) values (null, ?, ?, ?) [22001-200]
ca-list_1  | 2021-01-29 12:53:41.617 ERROR 1 --- [nio-8080-exec-1] n.m.r.controllers.RootCAController       : New root CA could not be persisted because it already exists
ca-list_1  | 
ca-list_1  | org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.DataException: could not execute statement
ca-list_1  | 	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:302) ~[spring-orm-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
ca-list_1  | 	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:255) ~[spring-orm-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
ca-list_1  | 	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:528) ~[spring-orm-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
```

**Comment by oliverhaagh** [comment]
Hmm, That sounds strange, the certificate column is defined as TEXT which, according to https://dev.mysql.com/doc/refman/8.0/en/storage-requirements.html#data-types-storage-reqs-strings, allows up to 2^16 characters. Could it be that you have an old version of the mysql docker image cached, because I am not able to reproduce the issue on my side?
